
# MySQL 설정 
spring:
  datasource:   
    url: jdbc:mysql://127.0.0.1:3306/jpashop_db
    username: root
    password: 1234   
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    
  jpa:
    hibernate:
      ddl-auto: create   # create-drop : Application이 종료 될 때 모든 테이블을 drop 시켜준다.
    show-sql: true      
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# logging:
#   file:
#     name: logs/apigateway.log
#     max-size: 500MB
#     max-history: 10
#   level:
#     root: info
#     '[com.mzc.apigateway_server]': debug
#     '[org.springframework.web]': DEBUG
#     '[reactor.core.publisher.Operators]': DEBUG
#     '[reactor]': DEBUG
